# Generated by Django 4.2.6 on 2023-10-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='distance_travelled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_consumption_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='truck',
            name='distance_travelled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel_consumption_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lane',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
