# Generated by Django 4.2.6 on 2023-12-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0002_car_distance_travelled_car_fuel_consumption_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadType', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='y',
            field=models.FloatField(default=0.0),
        ),
    ]
